apiVersion: v1
kind: Service

metadata:
  name: app1-service
  namespace: default
  labels:
    app: app1

spec:
  type: NodePort

  selector:
    app: app1

  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP                 