apiVersion: v1
kind: Service

metadata:
  name: calculator-service
  namespace: default
  labels:
    app: calculator

spec:
  type: NodePort

  selector:
    app: calculator

  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP                 