apiVersion: apps/v1
kind: Deployment

metadata:
  name: expense-tracker-deployment
  namespace: default
  labels:
    app: expense-tracker

spec:
  replicas: 2

  selector:
    matchLabels:
      app: expense-tracker

  template:
    metadata:
      labels:
        app: expense-tracker

    spec:
      imagePullSecrets:
        - name: zero-touch-registry

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: expense-tracker

      containers:
        - name: expense-tracker
          image: ghcr.io/salmarashedy/zero-touch/expense-tracker:5cdc2020a23b
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: 300m
              memory: 247Mi

            limits:
              cpu: 1000m
              memory: 1024Mi