apiVersion: v1
kind: Service

metadata:
  name: python-demoapp-service
  namespace: default
  labels:
    app: python-demoapp

spec:
  type: NodePort

  selector:
    app: python-demoapp

  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP                 