apiVersion: v1
kind: Service

metadata:
  name: ums-service
  namespace: default
  labels:
    app: ums

spec:
  type: NodePort

  selector:
    app: ums

  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP                 