apiVersion: apps/v1
kind: Deployment

metadata:
  name: weather-app1-deployment
  namespace: default
  labels:
    app: weather-app1

spec:
  replicas: 2

  selector:
    matchLabels:
      app: weather-app1

  template:
    metadata:
      labels:
        app: weather-app1

    spec:
      imagePullSecrets:
        - name: zero-touch-registry

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: weather-app1

      containers:
        - name: weather-app1
          image: ghcr.io/salmarashedy/zero-touch/weather-app1:3082673cb99d
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: 500m
              memory: 456Mi

            limits:
              cpu: 1000m
              memory: 1024Mi