apiVersion: apps/v1
kind: Deployment

metadata:
  name: weather-app-deployment
  namespace: default
  labels:
    app: weather-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: weather-app

  template:
    metadata:
      labels:
        app: weather-app

    spec:
      imagePullSecrets:
        - name: zero-touch-registry

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: weather-app

      containers:
        - name: weather-app
          image: ghcr.io/salmarashedy/zero-touch/weather-app:9eac449b3ace
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: 500m
              memory: 256Mi

            limits:
              cpu: 1000m
              memory: 1024Mi